### ISSUE TITLE
ctx.req is undefined

### ISSUE THREAD

**Issue by timrijkse** [dotneet/nuxt-device-detect#2]
When running `npm run generate` the `ctx.req` is always undefined meaning it always tries to get the navigator.userAgent which is undefined on the server:

```
 ReferenceError: navigator is not defined
```

I'm not sure what a solid fix would be but the following works for me (in plugin.js):

```
let userAgent = process.server ? '' : navigator.userAgent
```

**Comment by dotneet** [comment]
Hi @timrijkse, Thank you for reporting.

I've published new version of this module.
Please try it.

And check README.md.
I added the option for nuxt generate.

**Comment by timrijkse** [comment]
@dotneet Nice! That seems like a much neater solution.

All works fine here, thanks for the quick response :)
